spring:
  profiles:
    default: local
    group:
      local: local,secret
      dev: dev,secret
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

server:
  port: 8080